Jmol.___JmolDate="$Date: 2026-08-17 08:51:03 -0600 (Fri, 14 Aug 2026) $"
Jmol.___fullJmolProperties="src/org/jmol/viewer/Jmol.properties"
Jmol.___JmolVersion="16.4.22" // (swingJS) also 16.4.21 (legacy)
