Jmol.___JmolDate="$Date: 2026-05-06 14:02:50 -0600 (Wed, 6 May 2026) $"
Jmol.___fullJmolProperties="src/org/jmol/viewer/Jmol.properties"
Jmol.___JmolVersion="16.4.2" // (swingJS) also 16.4.1 (legacy)
