Jmol.___JmolDate="$Date: 2026-05-27 20:14:44 -0500 (Wed, 27 May 2026) $"
Jmol.___fullJmolProperties="src/org/jmol/viewer/Jmol.properties"
Jmol.___JmolVersion="16.4.4" // (swingJS) also 16.4.3 (legacy)
