/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jmol_multitouch_jni_JmolJniClientAdapter */

#ifndef _Included_org_jmol_multitouch_jni_JmolJniClientAdapter
#define _Included_org_jmol_multitouch_jni_JmolJniClientAdapter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jmol_multitouch_jni_JmolJniClientAdapter
 * Method:    nativeMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jmol_multitouch_jni_JmolJniClientAdapter_nativeMethod
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
